-- PokerBox minimal schema for auth + profile chips
-- Run in Supabase SQL editor.

create table if not exists public.players (
  id uuid primary key references auth.users(id) on delete cascade,
  nametag text not null unique,
  email text not null unique,
  chips integer not null default 10000,
  created_at timestamptz not null default now()
);

alter table public.players enable row level security;

drop policy if exists "players can read own profile" on public.players;
create policy "players can read own profile"
  on public.players
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "players can insert own profile" on public.players;
create policy "players can insert own profile"
  on public.players
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "players can update own profile" on public.players;
create policy "players can update own profile"
  on public.players
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create table if not exists public.rooms (
  code text primary key,
  host_id uuid not null references auth.users(id) on delete cascade,
  host_nametag text not null,
  status text not null default 'waiting',
  max_seats integer not null default 6,
  start_mode text,
  game_state jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  game_updated_at timestamptz
);

alter table public.rooms add column if not exists game_state jsonb;
alter table public.rooms add column if not exists game_updated_at timestamptz;

create table if not exists public.room_players (
  room_code text not null references public.rooms(code) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nametag text not null,
  joined_at timestamptz not null default now(),
  primary key (room_code, user_id)
);

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nametag text not null,
  text text not null check (char_length(text) between 1 and 180),
  created_at timestamptz not null default now()
);

alter table public.rooms enable row level security;
alter table public.room_players enable row level security;
alter table public.room_messages enable row level security;

drop policy if exists "authenticated users can read rooms" on public.rooms;
create policy "authenticated users can read rooms"
  on public.rooms
  for select
  to authenticated
  using (true);

drop policy if exists "users can create hosted rooms" on public.rooms;
create policy "users can create hosted rooms"
  on public.rooms
  for insert
  to authenticated
  with check (auth.uid() = host_id);

drop policy if exists "hosts can update rooms" on public.rooms;
create policy "hosts can update rooms"
  on public.rooms
  for update
  to authenticated
  using (
    auth.uid() = host_id
    or exists (
      select 1
      from public.room_players
      where room_players.room_code = rooms.code
        and room_players.user_id = auth.uid()
    )
  )
  with check (
    auth.uid() = host_id
    or exists (
      select 1
      from public.room_players
      where room_players.room_code = rooms.code
        and room_players.user_id = auth.uid()
    )
  );

drop policy if exists "hosts can delete rooms" on public.rooms;
create policy "hosts can delete rooms"
  on public.rooms
  for delete
  to authenticated
  using (auth.uid() = host_id);

drop policy if exists "authenticated users can read room players" on public.room_players;
create policy "authenticated users can read room players"
  on public.room_players
  for select
  to authenticated
  using (true);

drop policy if exists "users can join as themselves" on public.room_players;
create policy "users can join as themselves"
  on public.room_players
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "users can leave or hosts can kick" on public.room_players;
create policy "users can leave or hosts can kick"
  on public.room_players
  for delete
  to authenticated
  using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.rooms
      where rooms.code = room_players.room_code
        and rooms.host_id = auth.uid()
    )
  );

drop policy if exists "authenticated users can read room messages" on public.room_messages;
create policy "authenticated users can read room messages"
  on public.room_messages
  for select
  to authenticated
  using (true);

drop policy if exists "room members can send messages" on public.room_messages;
create policy "room members can send messages"
  on public.room_messages
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.room_players
      where room_players.room_code = room_messages.room_code
        and room_players.user_id = auth.uid()
    )
  );
